// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0uU-ifprb7dAaZ4z7CsQ9hleKdVJmua4',
    appId: '1:750810654886:web:de5c5f940b11b76db9ac67',
    messagingSenderId: '750810654886',
    projectId: 'job-finder-571c7',
    authDomain: 'job-finder-571c7.firebaseapp.com',
    storageBucket: 'job-finder-571c7.firebasestorage.app',
    measurementId: 'G-E59T1B5XJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQK4AwHS_5XOBqK2R56PbCKFI95Q5NIyA',
    appId: '1:750810654886:android:f257ce74c5611ce8b9ac67',
    messagingSenderId: '750810654886',
    projectId: 'job-finder-571c7',
    storageBucket: 'job-finder-571c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC6_RsVutZqZ2z4IpAYLX9LpiSyPdVnZA',
    appId: '1:750810654886:ios:b6ba113508f8aee5b9ac67',
    messagingSenderId: '750810654886',
    projectId: 'job-finder-571c7',
    storageBucket: 'job-finder-571c7.firebasestorage.app',
    androidClientId: '750810654886-dv56bnqtc40e5o40tfnekkrudrius4cb.apps.googleusercontent.com',
    iosClientId: '750810654886-smu8gvuh0sidjbpa873ldmk1qutfhdug.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC6_RsVutZqZ2z4IpAYLX9LpiSyPdVnZA',
    appId: '1:750810654886:ios:b6ba113508f8aee5b9ac67',
    messagingSenderId: '750810654886',
    projectId: 'job-finder-571c7',
    storageBucket: 'job-finder-571c7.firebasestorage.app',
    androidClientId: '750810654886-dv56bnqtc40e5o40tfnekkrudrius4cb.apps.googleusercontent.com',
    iosClientId: '750810654886-smu8gvuh0sidjbpa873ldmk1qutfhdug.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0uU-ifprb7dAaZ4z7CsQ9hleKdVJmua4',
    appId: '1:750810654886:web:fb4de9cdaa7fbb17b9ac67',
    messagingSenderId: '750810654886',
    projectId: 'job-finder-571c7',
    authDomain: 'job-finder-571c7.firebaseapp.com',
    storageBucket: 'job-finder-571c7.firebasestorage.app',
    measurementId: 'G-BYC6BJD5S9',
  );

}